<?php
/**
 * Taxdoo_VAT
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxdoo
 * @package    Taxdoo_VAT
 * @copyright  Copyright (c) 2017 TaxJar. TaxJar is a trademark of TPS Unlimited, Inc. (http://www.taxjar.com)
 * @copyright  Copyright (c) 2021 Andrea Lazzaretti.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile

?>
<?php
$order = $block->getOrder();
$orderSyncDate = '';

if ($block->getSyncedAtDate($order)) {
    $orderSyncDate = $block->formatDate(
        new \DateTime($block->getSyncedAtDate($order)),
        \IntlDateFormatter::MEDIUM,
        true
    );
}
?>
<?php if (!empty($orderSyncDate)): ?>
<tr>
    <th><?php /* @escapeNotVerified */ echo __('Synced to Taxdoo (or sandbox)') ?></th>
    <td><?php /* @escapeNotVerified */ echo $orderSyncDate ?></td>
</tr>
<?php endif; ?>
