<?php
/**
 * Taxdoo_VAT
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxdoo
 * @package    Taxdoo_VAT
 * @copyright  Copyright (c) 2021 Andrea Lazzaretti.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \Magento\Framework\View\Element\Template $block */

$acceptedMsg = __('Taxdoo seems to have accepted your API Token. Does your Taxdoo email look like this? ');
$rejectedMsg = __('The Taxdoo API Token seems to be wrong. You can find the correct one in the ');
$urlApiKey = 'https://dashboard.taxdoo.com/api_keys.php';
$href = '<a href="%1" target="_blank" rel="noopener">' . __('Taxdoo Dashboard') . '</a>';


if($block->getData('accepted')) {
  echo $block->escapeHtml(__($acceptedMsg . ' ' . obfuscate_email($block->getData('response')['account']) ), ['div']);
} else {
  echo $block->escapeHtml(__($rejectedMsg . ' ' . $href, [$urlApiKey]), ['a']);
}

/*
 * Many thanks to msturdy from stackoverflow for this function : https://stackoverflow.com/a/20545505
 */

function obfuscate_email($email)
{
    $em   = explode("@",$email);
    $name = implode('@', array_slice($em, 0, count($em)-1));
    if (strlen($name) >= 3) {
      $len = 3;
      $asterisks = strlen($name) - 3;
    } else {
      $len = 0;
      $asterisks = strlen($name);
    }

    return substr($name,0, $len) . str_repeat('*', $asterisks) . "@" . end($em);
}
