<?php
/**
 * Taxdoo_VAT
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Taxdoo
 * @package    Taxdoo_VAT
 * @copyright  Copyright (c) 2020 TaxJar.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \Magento\Framework\View\Element\Template $block */

$acceptedMsg = __('Taxdoo seems to have accepted your API Token. Is this your Taxdoo email? ');
$rejectedMsg = __('The Taxdoo API Token seems to be wrong. You can find the correct one in the ');
$urlApiKey = 'https://dashboard.taxdoo.com/api_keys.php';
$href = '<a href="%1" target="_blank" rel="noopener">' . __('Taxdoo Dashbaord') . '</a>';


if($block->getData('accepted')) {
  echo $block->escapeHtml(__($acceptedMsg . ' ' . $block->getData('response')['account'] ), ['div']);
} else {
  //echo $block->escapeHtml(__($rejectedMsg), ['div']);
  echo $block->escapeHtml(__($rejectedMsg . ' ' . $href, [$urlApiKey]), ['a']);
}
